### ISSUE TITLE
contextIsolation : false is very dangerous.

### ISSUE THREAD

**Issue by yongwookim** [AgoraIO-Extensions/Electron-SDK#976]
Current version of agora Electron SDK only works when Context Isolation is set as false. 
As you know, contextIsolation is default for Electron and it is recommended security setting for ALL apps. 

Do you have plans to update the SDK to support Context Isolation?

**Comment by LichKing-2234** [comment]
Sorry, we can not support it because of the platform restrictions.

**Comment by AlexShemelin** [comment]
I suppose these are consequences of using browser API (keywords such as 'window', 'navigator', etc.) and Node.js API in one codebase. Personally, I would rename this repo to "Node.js Agora SDK" and remove all code related to the browser (because one can easily use agora-rtc-sdk-ng for browser functionality).
